version: "3.9"
services:
  mariadb:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hexamgen
      MARIADB_USER: hexamgen
      MARIADB_PASSWORD: hexamgen
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: mysql+asyncmy://hexamgen:hexamgen@mariadb:3306/hexamgen?charset=utf8mb4
      FRONTEND_ORIGIN: http://localhost:3000
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
volumes:
  mariadb_data:
