version: '3.8'
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hexamgen
      MYSQL_USER: hexamgen
      MYSQL_PASSWORD: hexamgen
    ports:
      - "3306:3306"
    volumes:
      - ./backend/config/my.cnf:/etc/mysql/conf.d/my.cnf