version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ved        
      POSTGRES_PASSWORD: v
      POSTGRES_DB: hexamgen
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/hexamgen
      SECRET_KEY: supersecret
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
